version: '2'
services:
  cinematica-app:
    image: cinematica
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://cinematica-mysql:3306/cinematica?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://cinematica-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://cinematica-elasticsearch:9200
    ports:
      - 8080:8080
  cinematica-mysql:
    extends:
      file: mysql.yml
      service: cinematica-mysql
  cinematica-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: cinematica-elasticsearch
